In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")
import datetime

from kiblib.utils.db import DbConn

In [2]:
db_conn = DbConn().create_engine()

In [166]:
today = datetime.datetime.now()

#dates = [datetime.date(2023, d, 1).strftime("%Y-%m-%d") for d in range(1, 13)]
#dates.extend([datetime.date(2024, d, 1).strftime("%Y-%m-%d") for d in range(1, 13)])
#dates.extend([datetime.date(2025, d, 1).strftime("%Y-%m-%d") for d in range(1, 7)])
#dates

# tous les mardis entre deux dates extrêmes
start, end = datetime.datetime(2024, 1, 1), datetime.datetime(2025, 1, 1)
days = (start + datetime.timedelta(days=i) for i in range((end - start).days + 1))
dates = [d.strftime("%Y-%m-%d") for d in days if d.weekday() == 1 ]

In [158]:
prets_all = pd.DataFrame()
for date in dates:
    print(date)
    query = f"SELECT * FROM statdb.stat_issues WHERE DATE(issuedate) <= '{date}' AND DATE(date_due) > '{date}' AND ( DATE(returndate) > '{date}' OR returndate IS NULL)"
    prets = pd.read_sql(query, con=db_conn)
    prets['date_pivot'] = date
    prets = prets[prets['categorycode'].isin(['BIBL', 'MEDA', 'MEDB', 'MEDC', 'CSVT'])]

    prets['issuedate_'] = pd.to_datetime(prets['issuedate'])
    prets['date_due_'] = pd.to_datetime(prets['date_due'])
    prets['returndate_'] = pd.to_datetime(prets['returndate'])

    prets.loc[~prets['returndate'].isna(), 'retard'] = round( (prets['returndate_'] - prets['date_due_']) / np.timedelta64(1, 'D'), 1 )
    prets.loc[prets['returndate'].isna(), 'retard'] = round( (today - prets['date_due_']) / np.timedelta64(1, 'D'), 1 )

    prets['retard?'] = np.nan
    prets.loc[(prets['retard?'].isna()) & (prets['retard'] <= 0), 'retard?'] = '0 - pas de retard'
    prets.loc[(prets['retard?'].isna()) & (prets['retard'] > 180), 'retard?'] = '7 - contentieux 180 jours'
    prets.loc[(prets['retard?'].isna()) & (prets['retard'] > 90), 'retard?'] = '6 - contentieux 90 jours'
    prets.loc[(prets['retard?'].isna()) & (prets['retard'] > 42), 'retard?'] = '5 - contentieux'
    prets.loc[(prets['retard?'].isna()) & (prets['retard'] > 28), 'retard?'] = '4 - retard > 28 jours'
    prets.loc[(prets['retard?'].isna()) & (prets['retard'] > 14), 'retard?'] = '3 - retard > 14 jours'
    prets.loc[(prets['retard?'].isna()) & (prets['retard'] > 7), 'retard?'] = '2 - retard > 7 jours'
    prets.loc[(prets['retard?'].isna()) & (prets['retard'] > 0), 'retard?'] = '1 - retard <= 7 jours'    

    prets_all = pd.concat([prets_all, prets])

2024-01-02
2024-01-09
2024-01-16
2024-01-23
2024-01-30
2024-02-06
2024-02-13
2024-02-20
2024-02-27
2024-03-05
2024-03-12
2024-03-19
2024-03-26
2024-04-02
2024-04-09
2024-04-16
2024-04-23
2024-04-30
2024-05-07
2024-05-14
2024-05-21
2024-05-28
2024-06-04
2024-06-11
2024-06-18
2024-06-25
2024-07-02
2024-07-09
2024-07-16
2024-07-23
2024-07-30
2024-08-06
2024-08-13
2024-08-20
2024-08-27
2024-09-03
2024-09-10
2024-09-17
2024-09-24
2024-10-01
2024-10-08
2024-10-15
2024-10-22
2024-10-29
2024-11-05
2024-11-12
2024-11-19
2024-11-26
2024-12-03
2024-12-10
2024-12-17
2024-12-24
2024-12-31
2025-01-07
2025-01-14
2025-01-21
2025-01-28
2025-02-04
2025-02-11
2025-02-18
2025-02-25
2025-03-04
2025-03-11
2025-03-18
2025-03-25
2025-04-01
2025-04-08
2025-04-15
2025-04-22

KeyboardInterrupt:

In [168]:
prets_all = prets_all[~prets_all['date_pivot'].isin(['2025-01-07', '2025-01-14', '2025-01-21', 
                                                     '2025-01-28', '2025-02-04', '2025-02-11',
                                                     '2025-02-18', '2025-02-25', '2025-03-04',
                                                     '2025-03-11', '2025-03-18', '2025-03-25',
                                                     '2025-04-01', '2025-04-08', '2025-04-15'])]

In [169]:
prets_all['date_pivot'].unique()

array(['2024-01-02', '2024-01-09', '2024-01-16', '2024-01-23',
       '2024-01-30', '2024-02-06', '2024-02-13', '2024-02-20',
       '2024-02-27', '2024-03-05', '2024-03-12', '2024-03-19',
       '2024-03-26', '2024-04-02', '2024-04-09', '2024-04-16',
       '2024-04-23', '2024-04-30', '2024-05-07', '2024-05-14',
       '2024-05-21', '2024-05-28', '2024-06-04', '2024-06-11',
       '2024-06-18', '2024-06-25', '2024-07-02', '2024-07-09',
       '2024-07-16', '2024-07-23', '2024-07-30', '2024-08-06',
       '2024-08-13', '2024-08-20', '2024-08-27', '2024-09-03',
       '2024-09-10', '2024-09-17', '2024-09-24', '2024-10-01',
       '2024-10-08', '2024-10-15', '2024-10-22', '2024-10-29',
       '2024-11-05', '2024-11-12', '2024-11-19', '2024-11-26',
       '2024-12-03', '2024-12-10', '2024-12-17', '2024-12-24',
       '2024-12-31'], dtype=object)

In [163]:
table = prets_all.pivot_table(index='date_pivot', columns=['retard?'], values=['issue_id'],
                              aggfunc={'issue_id': "count"},
                              margins=True,
                              margins_name= 'Total'
                             )
table

                    issue_id                                             \
retard?    0 - pas de retard 1 - retard <= 7 jours 2 - retard > 7 jours
date_pivot
2024-01-02              9404                  2766                 1401
2024-01-09              9327                  2733                 1452
2024-01-16              9875                  2608                 1291
2024-01-23             10315                  2317                 1022
2024-01-30             10599                  2396                 1151
2024-02-06             11106                  2413                 1269
2024-02-13             11041                  2494                 1427
2024-02-20             10922                  2684                 1381
2024-02-27             10601                  2855                 1518
2024-03-05             10430                  3029                 1601
2024-03-12             10232                  2627                 1479
2024-03-19             10298                  2739                 1422
2024-03-26             10534                  2759                 1413
2024-04-02             10413                  2910                 1486
2024-04-09              9894                  2530                 1306
2024-04-16              9671                  2225                 1266
2024-04-23              9229                  2752                 1320
2024-04-30              9771                  2784                 1621
2024-05-07              9196                  2951                 1608
2024-05-14              9049                  2056                 1335
2024-05-21              9468                  2029                 1086
2024-05-28              9164                  2028                 1106
2024-06-04              8772                  2123                 1283
2024-06-11              8245                  2570                 1362
2024-06-18              8333                  2298                 1095
2024-06-25              8559                  2158                  965
2024-07-02              8927                  1762                 1023
2024-07-09              8722                  2018                 1429
2024-07-16              9019                  2386                 1652
2024-07-23              8672                  2344                 1496
2024-07-30              8424                  2325                 1360
2024-08-06              7979                  2374                 1300
2024-08-13              7961                  2514                 1277
2024-08-20              8355                  2319                 1207
2024-08-27              8621                  2146                 1217
2024-09-03              8771                  2209                 1157
2024-09-10              9550                  2465                 1101
2024-09-17              9865                  2421                 1126
2024-09-24             10090                  2409                 1289
2024-10-01             10121                  2487                 1482
2024-10-08             10524                  2526                 1530
2024-10-15             10479                  2535                 1582
2024-10-22             10544                  2907                 1609
2024-10-29             10494                  2892                 1624
2024-11-05             10367                  2661                 1408
2024-11-12             10619                  2251                 1289
2024-11-19             10838                  2462                 1365
2024-11-26             11033                  2502                 1268
2024-12-03             10529                  2231                 1352
2024-12-10              9984                  2103                 1328
2024-12-17              9127                  2297                 1322
2024-12-24              8531                  2124                 1280
2024-12-31              8040                  2119                 1032
2025-01-07              7192                  1986                 1212
2025-01-14              7245                  2316                 1082
2025-01-21              8001                  2130                  986
Total                 533072                136055                74051

                                                                        \
retard?    3 - retard > 14 jours 4 - retard > 28 jours 5 - contentieux
date_pivot
2024-01-02                  2607                   603             384
2024-01-09                  2563                   529             381
2024-01-16                  2296                   528             366
2024-01-23                  1982                   533             390
2024-01-30                  1945                   703             365
2024-02-06                  2236                   813             405
2024-02-13                  2400                   735             410
2024-02-20                  2510                   634             417
2024-02-27                  2392                   633             540
2024-03-05                  2391                   830             492
2024-03-12                  2176                   818             506
2024-03-19                  2319                   759             399
2024-03-26                  2174                   666             438
2024-04-02                  2210                   710             477
2024-04-09                  2171                   640             462
2024-04-16                  2236                   611             398
2024-04-23                  2410                   551             415
2024-04-30                  2376                   629             511
2024-05-07                  2248                   608             553
2024-05-14                  1842                   645             461
2024-05-21                  1840                   589             368
2024-05-28                  2001                   565             388
2024-06-04                  2083                   523             431
2024-06-11                  1929                   537             404
2024-06-18                  1601                   451             379
2024-06-25                  1664                   450             408
2024-07-02                  1648                   515             474
2024-07-09                  2207                   680             493
2024-07-16                  2488                   727             457
2024-07-23                  2633                   623             403
2024-07-30                  2678                   488             338
2024-08-06                  2634                   428             300
2024-08-13                  2333                   498             245
2024-08-20                  1857                   528             236
2024-08-27                  1501                   560             254
2024-09-03                  1705                   607             297
2024-09-10                  1968                   645             331
2024-09-17                  2164                   698             295
2024-09-24                  2184                   642             274
2024-10-01                  2342                   659             273
2024-10-08                  2333                   592             364
2024-10-15                  2269                   595             420
2024-10-22                  2175                   585             487
2024-10-29                  2302                   669             521
2024-11-05                  2275                   673             526
2024-11-12                  2311                   739             550
2024-11-19                  2197                   832             482
2024-11-26                  2365                   743             503
2024-12-03                  2221                   660             503
2024-12-10                  2040                   576             481
2024-12-17                  1938                   623             436
2024-12-24                  1888                   573             371
2024-12-31                  1944                   510             327
2025-01-07                  1870                   505             279
2025-01-14                  1655                   492             256
2025-01-21                  1572                   425             261
Total                     120299                 34383           22585


retard?    6 - contentieux 90 jours 7 - contentieux 180 jours   Total
date_pivot
2024-01-02                       83                       150   17398
2024-01-09                       83                       136   17204
2024-01-16                       66                       138   17168
2024-01-23                       64                       129   16752
2024-01-30                       66                       119   17344
2024-02-06                       53                       131   18426
2024-02-13                       35                       146   18688
2024-02-20                       82                       160   18790
2024-02-27                      101                       173   18813
2024-03-05                       91                       175   19039
2024-03-12                       69                       194   18101
2024-03-19                       65                       182   18183
2024-03-26                       66                       174   18224
2024-04-02                       40                       167   18413
2024-04-09                       35                       176   17214
2024-04-16                       30                       202   16639
2024-04-23                       49                       312   17038
2024-04-30                       55                       434   18181
2024-05-07                       80                       575   17819
2024-05-14                       70                       575   16033
2024-05-21                       65                       693   16138
2024-05-28                       58                      1012   16322
2024-06-04                       45                      1301   16561
2024-06-11                       40                      1311   16398
2024-06-18                       31                       871   15059
2024-06-25                       35                       536   14775
2024-07-02                       38                       297   14684
2024-07-09                       25                       217   15791
2024-07-16                       36                       138   16903
2024-07-23                       44                        88   16303
2024-07-30                       42                        90   15745
2024-08-06                       55                        86   15156
2024-08-13                       47                        92   14967
2024-08-20                       67                       106   14675
2024-08-27                       42                       104   14445
2024-09-03                       61                       121   14928
2024-09-10                       73                       145   16278
2024-09-17                      109                       156   16834
2024-09-24                       80                       158   17126
2024-10-01                       92                       139   17595
2024-10-08                       68                       147   18084
2024-10-15                       73                       185   18138
2024-10-22                       47                       196   18550
2024-10-29                       43                       253   18798
2024-11-05                       51                       223   18184
2024-11-12                       54                       338   18151
2024-11-19                       58                       514   18748
2024-11-26                       56                       717   19187
2024-12-03                       40                      1011   18547
2024-12-10                       39                      1506   18057
2024-12-17                      110                      1817   17670
2024-12-24                      228                      2041   17036
2024-12-31                      312                      2075   16359
2025-01-07                      952                      1955   15951
2025-01-14                     1511                      1374   15931
2025-01-21                     1593                       564   15532
Total                          7603                     27025  955073

In [164]:
table2 =table.div(table.iloc[:,-1], axis=0 )
table2

                    issue_id                                             \
retard?    0 - pas de retard 1 - retard <= 7 jours 2 - retard > 7 jours
date_pivot
2024-01-02          0.540522              0.158984             0.080526
2024-01-09          0.542141              0.158858             0.084399
2024-01-16          0.575198              0.151911             0.075198
2024-01-23          0.615747              0.138312             0.061008
2024-01-30          0.611105              0.138146             0.066363
2024-02-06          0.602735              0.130956             0.068870
2024-02-13          0.590807              0.133455             0.076359
2024-02-20          0.581267              0.142842             0.073497
2024-02-27          0.563493              0.151757             0.080689
2024-03-05          0.547823              0.159094             0.084091
2024-03-12          0.565273              0.145130             0.081708
2024-03-19          0.566353              0.150635             0.078205
2024-03-26          0.578029              0.151394             0.077535
2024-04-02          0.565524              0.158041             0.080704
2024-04-09          0.574765              0.146973             0.075868
2024-04-16          0.581225              0.133722             0.076086
2024-04-23          0.541672              0.161521             0.077474
2024-04-30          0.537429              0.153127             0.089159
2024-05-07          0.516078              0.165610             0.090241
2024-05-14          0.564398              0.128236             0.083266
2024-05-21          0.586690              0.125728             0.067295
2024-05-28          0.561451              0.124249             0.067761
2024-06-04          0.529678              0.128193             0.077471
2024-06-11          0.502805              0.156726             0.083059
2024-06-18          0.553357              0.152600             0.072714
2024-06-25          0.579289              0.146058             0.065313
2024-07-02          0.607941              0.119995             0.069668
2024-07-09          0.552340              0.127794             0.090495
2024-07-16          0.533574              0.141158             0.097734
2024-07-23          0.531927              0.143777             0.091762
2024-07-30          0.535027              0.147666             0.086377
2024-08-06          0.526458              0.156638             0.085775
2024-08-13          0.531904              0.167970             0.085321
2024-08-20          0.569336              0.158024             0.082249
2024-08-27          0.596816              0.148564             0.084251
2024-09-03          0.587554              0.147977             0.077505
2024-09-10          0.586681              0.151431             0.067637
2024-09-17          0.586016              0.143816             0.066888
2024-09-24          0.589163              0.140663             0.075266
2024-10-01          0.575220              0.141347             0.084228
2024-10-08          0.581951              0.139681             0.084605
2024-10-15          0.577737              0.139762             0.087220
2024-10-22          0.568410              0.156712             0.086739
2024-10-29          0.558251              0.153846             0.086392
2024-11-05          0.570117              0.146337             0.077431
2024-11-12          0.585037              0.124015             0.071015
2024-11-19          0.578088              0.131321             0.072808
2024-11-26          0.575025              0.130401             0.066086
2024-12-03          0.567693              0.120289             0.072896
2024-12-10          0.552916              0.116465             0.073545
2024-12-17          0.516525              0.129994             0.074816
2024-12-24          0.500763              0.124677             0.075135
2024-12-31          0.491473              0.129531             0.063085
2025-01-07          0.450881              0.124506             0.075983
2025-01-14          0.454774              0.145377             0.067918
2025-01-21          0.515130              0.137136             0.063482
Total               0.558148              0.142455             0.077534

                                                                        \
retard?    3 - retard > 14 jours 4 - retard > 28 jours 5 - contentieux
date_pivot
2024-01-02              0.149845              0.034659        0.022072
2024-01-09              0.148977              0.030749        0.022146
2024-01-16              0.133737              0.030755        0.021319
2024-01-23              0.118314              0.031817        0.023281
2024-01-30              0.112143              0.040533        0.021045
2024-02-06              0.121350              0.044122        0.021980
2024-02-13              0.128425              0.039330        0.021939
2024-02-20              0.133582              0.033741        0.022193
2024-02-27              0.127146              0.033647        0.028704
2024-03-05              0.125584              0.043595        0.025842
2024-03-12              0.120214              0.045191        0.027954
2024-03-19              0.127537              0.041742        0.021944
2024-03-26              0.119293              0.036545        0.024034
2024-04-02              0.120024              0.038560        0.025906
2024-04-09              0.126118              0.037179        0.026839
2024-04-16              0.134383              0.036721        0.023920
2024-04-23              0.141449              0.032339        0.024357
2024-04-30              0.130686              0.034597        0.028106
2024-05-07              0.126157              0.034121        0.031034
2024-05-14              0.114888              0.040230        0.028753
2024-05-21              0.114017              0.036498        0.022803
2024-05-28              0.122595              0.034616        0.023772
2024-06-04              0.125777              0.031580        0.026025
2024-06-11              0.117636              0.032748        0.024637
2024-06-18              0.106315              0.029949        0.025168
2024-06-25              0.112623              0.030457        0.027614
2024-07-02              0.112231              0.035072        0.032280
2024-07-09              0.139763              0.043063        0.031220
2024-07-16              0.147193              0.043010        0.027037
2024-07-23              0.161504              0.038214        0.024719
2024-07-30              0.170086              0.030994        0.021467
2024-08-06              0.173793              0.028240        0.019794
2024-08-13              0.155876              0.033273        0.016369
2024-08-20              0.126542              0.035980        0.016082
2024-08-27              0.103911              0.038768        0.017584
2024-09-03              0.114215              0.040662        0.019895
2024-09-10              0.120899              0.039624        0.020334
2024-09-17              0.128549              0.041464        0.017524
2024-09-24              0.127525              0.037487        0.015999
2024-10-01              0.133106              0.037454        0.015516
2024-10-08              0.129009              0.032736        0.020128
2024-10-15              0.125096              0.032804        0.023156
2024-10-22              0.117251              0.031536        0.026253
2024-10-29              0.122460              0.035589        0.027716
2024-11-05              0.125110              0.037011        0.028927
2024-11-12              0.127321              0.040714        0.030301
2024-11-19              0.117186              0.044378        0.025709
2024-11-26              0.123261              0.038724        0.026216
2024-12-03              0.119750              0.035585        0.027120
2024-12-10              0.112976              0.031899        0.026638
2024-12-17              0.109677              0.035257        0.024675
2024-12-24              0.110824              0.033635        0.021777
2024-12-31              0.118834              0.031175        0.019989
2025-01-07              0.117234              0.031659        0.017491
2025-01-14              0.103886              0.030883        0.016069
2025-01-21              0.101210              0.027363        0.016804
Total                   0.125958              0.036000        0.023647


retard?    6 - contentieux 90 jours 7 - contentieux 180 jours Total
date_pivot
2024-01-02                 0.004771                  0.008622   1.0
2024-01-09                 0.004824                  0.007905   1.0
2024-01-16                 0.003844                  0.008038   1.0
2024-01-23                 0.003820                  0.007701   1.0
2024-01-30                 0.003805                  0.006861   1.0
2024-02-06                 0.002876                  0.007110   1.0
2024-02-13                 0.001873                  0.007812   1.0
2024-02-20                 0.004364                  0.008515   1.0
2024-02-27                 0.005369                  0.009196   1.0
2024-03-05                 0.004780                  0.009192   1.0
2024-03-12                 0.003812                  0.010718   1.0
2024-03-19                 0.003575                  0.010009   1.0
2024-03-26                 0.003622                  0.009548   1.0
2024-04-02                 0.002172                  0.009070   1.0
2024-04-09                 0.002033                  0.010224   1.0
2024-04-16                 0.001803                  0.012140   1.0
2024-04-23                 0.002876                  0.018312   1.0
2024-04-30                 0.003025                  0.023871   1.0
2024-05-07                 0.004490                  0.032269   1.0
2024-05-14                 0.004366                  0.035864   1.0
2024-05-21                 0.004028                  0.042942   1.0
2024-05-28                 0.003553                  0.062002   1.0
2024-06-04                 0.002717                  0.078558   1.0
2024-06-11                 0.002439                  0.079949   1.0
2024-06-18                 0.002059                  0.057839   1.0
2024-06-25                 0.002369                  0.036277   1.0
2024-07-02                 0.002588                  0.020226   1.0
2024-07-09                 0.001583                  0.013742   1.0
2024-07-16                 0.002130                  0.008164   1.0
2024-07-23                 0.002699                  0.005398   1.0
2024-07-30                 0.002668                  0.005716   1.0
2024-08-06                 0.003629                  0.005674   1.0
2024-08-13                 0.003140                  0.006147   1.0
2024-08-20                 0.004566                  0.007223   1.0
2024-08-27                 0.002908                  0.007200   1.0
2024-09-03                 0.004086                  0.008106   1.0
2024-09-10                 0.004485                  0.008908   1.0
2024-09-17                 0.006475                  0.009267   1.0
2024-09-24                 0.004671                  0.009226   1.0
2024-10-01                 0.005229                  0.007900   1.0
2024-10-08                 0.003760                  0.008129   1.0
2024-10-15                 0.004025                  0.010200   1.0
2024-10-22                 0.002534                  0.010566   1.0
2024-10-29                 0.002287                  0.013459   1.0
2024-11-05                 0.002805                  0.012264   1.0
2024-11-12                 0.002975                  0.018622   1.0
2024-11-19                 0.003094                  0.027416   1.0
2024-11-26                 0.002919                  0.037369   1.0
2024-12-03                 0.002157                  0.054510   1.0
2024-12-10                 0.002160                  0.083403   1.0
2024-12-17                 0.006225                  0.102830   1.0
2024-12-24                 0.013383                  0.119805   1.0
2024-12-31                 0.019072                  0.126841   1.0
2025-01-07                 0.059683                  0.122563   1.0
2025-01-14                 0.094847                  0.086247   1.0
2025-01-21                 0.102562                  0.036312   1.0
Total                      0.007961                  0.028296   1.0

In [170]:
table2.to_excel("test.xlsx")

In [172]:
p = prets_all[prets_all['retard?'] == '7 - contentieux 180 jours']
p2 = p[p['date_pivot'] == '2024-12-17']

In [173]:
p2

,issuedate,date_due,returndate,renewals,branch,arret_bus,borrowernumber,cardnumber,age,sexe,...,cle,timestamp,issue_id,returnbranch,date_pivot,issuedate_,date_due_,returndate_,retard,retard?
10200,2024-11-06 11:05:10,2024-12-18 23:59:00,NaT,1,MED,None,23468,X0002491691,51,F,...,2024-11-06 11:05:10-466878,2024-11-08 03:12:06,5112087,None,2024-12-17,2024-11-06 11:05:10,2024-12-18 23:59:00,NaT,217.7,7 - contentieux 180 jours
10219,2024-11-06 12:25:59,2024-12-18 23:59:00,NaT,1,MED,None,76243,X0002734514,12,F,...,2024-11-06 12:25:59-421475,2024-11-08 03:12:06,5112419,None,2024-12-17,2024-11-06 12:25:59,2024-12-18 23:59:00,NaT,217.7,7 - contentieux 180 jours
10220,2024-11-06 12:26:04,2024-12-18 23:59:00,NaT,1,MED,None,76243,X0002734514,12,F,...,2024-11-06 12:26:04-401945,2024-11-08 03:12:06,5112420,None,2024-12-17,2024-11-06 12:26:04,2024-12-18 23:59:00,NaT,217.7,7 - contentieux 180 jours
10222,2024-11-06 12:30:23,2024-12-18 23:59:00,NaT,1,MED,None,76243,X0002734514,12,F,...,2024-11-06 12:30:23-465628,2024-11-08 03:12:06,5112424,None,2024-12-17,2024-11-06 12:30:23,2024-12-18 23:59:00,NaT,217.7,7 - contentieux 180 jours
10223,2024-11-06 12:30:26,2024-12-18 23:59:00,NaT,1,MED,None,76243,X0002734514,12,F,...,2024-11-06 12:30:26-475646,2024-11-08 03:12:06,5112425,None,2024-12-17,2024-11-06 12:30:26,2024-12-18 23:59:00,NaT,217.7,7 - contentieux 180 jours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30352,2024-12-17 18:02:49,2025-01-07 23:59:00,NaT,0,BUS,B03,73890,X0002752785,11,F,...,2024-12-17 18:02:49-347590,2024-12-19 03:12:28,5171817,None,2024-12-17,2024-12-17 18:02:49,2025-01-07 23:59:00,NaT,197.7,7 - contentieux 180 jours
30353,2024-12-17 18:02:53,2025-01-07 23:59:00,NaT,0,BUS,B03,73890,X0002752785,11,F,...,2024-12-17 18:02:53-479698,2024-12-19 03:12:28,5171818,None,2024-12-17,2024-12-17 18:02:53,2025-01-07 23:59:00,NaT,197.7,7 - contentieux 180 jours
30354,2024-12-17 18:03:15,2025-01-07 23:59:00,NaT,0,BUS,B03,79364,X0002611921,7,F,...,2024-12-17 18:03:15-314081,2024-12-19 03:12:28,5171819,None,2024-12-17,2024-12-17 18:03:15,2025-01-07 23:59:00,NaT,197.7,7 - contentieux 180 jours
30355,2024-12-17 18:03:20,2025-01-07 23:59:00,NaT,0,BUS,B03,79364,X0002611921,7,F,...,2024-12-17 18:03:20-384218,2024-12-19 03:12:28,5171820,None,2024-12-17,2024-12-17 18:03:20,2025-01-07 23:59:00,NaT,197.7,7 - contentieux 180 jours
30398,2024-12-17 18:33:09,2025-01-07 23:59:00,NaT,0,MED,None,79956,X0002721415,31,F,...,2024-12-17 18:33:09-415700,2024-12-19 03:12:28,5171863,None,2024-12-17,2024-12-17 18:33:09,2025-01-07 23:59:00,NaT,197.7,7 - contentieux 180 jours