# NOTEBOOK RAPPORT SLL

L'objectif de ce notebook est de remplir le rapport du Service du Livre et de la Lecture (SLL).

# A - Site internet

## A1 - Site internet

* Site internet 
* Statut site : Site internet propre

La bibliothèque a-t-elle déposé une attestation de conformité de son site web aux exigences du Référentiel général d'accessibilité pour les administrations RGAA) ? **Non**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")
import datetime

from kiblib.utils.db import DbConn
from kiblib.utils.code2libelle import Code2Libelle
from kiblib.adherent import Adherent
from kiblib.pret import Pret
from kiblib.document import Document

In [2]:
db_conn = DbConn().create_engine()

year = 2025
#date_extraction_usagers = '2023-12-27'
date_extraction_usagers = '2025-12-31'

# C - Accès et installations
## C1 - Accès et installations

|Nombre d'heures d'ouverture hebdomadaires tous publics|54|C101|
|:-----------------------------------------------------|---|----|
|Nombre de jours d'ouverture hebdomadaires|6|C115|
|Nombre de jours d'ouverture annuels|???|C102|
|La bibliothèque est-elle ouverte dimanche ?|Oui|C116|
|Nombre de places assises disponibles |232|C103 | 
| - Avec possibilité de connexions aux ordinateurs |47|C104|
|Nombre de postes informatiques publics avec accès internet|???|C106|
|La bibliothèque met-elle à disposition des usagers empêchés de lire du fait d’un handicap, des postes informatiques équipés d’aides matérielles et logicielles pour accéder aux collections ?|Non|C114|
|Nombre de photocopieurs en accès public| 1|C109|
|Nombre d'imprimantes en accès public|3|C110
|Nombre de tablettes mises à disposition du public|0|C118|
|Nombre de bibliobus|1|C112
|Liseuses mises à la dispsition du public|0|C118|
|Bornes d'écoute|1|C119|
|Nombre de consoles de jeux-vidéos|6|C121|
|Connexion wifi publique|oui|C120|

In [3]:
from datetime import datetime as dt

In [4]:
query = f"""SELECT datetime, entrees
FROM statdb.stat_entrees
WHERE YEAR(datetime)={year}"""

In [5]:
df = pd.read_sql(query,db_conn)

In [6]:
df["date"] = pd.to_datetime(df['datetime']).dt.date

In [7]:
df = df.groupby('date')['entrees'].sum().to_frame()

In [8]:
C102_NbJoursDouvertureAnnuels = len(df[(df['entrees']>50)])
print(f"C102 - Nombre de jours d'ouverture annuels : {C102_NbJoursDouvertureAnnuels}")

C102 - Nombre de jours d'ouverture annuels : 283

## C2 - Catalogue

### Notices

In [9]:
query = f"""SELECT COUNT(bm.biblionumber)
    FROM koha{year}.biblio_metadata bm"""
r = pd.read_sql(query, db_conn)
r

   COUNT(bm.biblionumber)
0                  232577

### Notices créées dans l'année

In [10]:
query = f"""SELECT COUNT(bm.biblionumber)
    FROM koha{year}.biblio_metadata bm
    JOIN koha{year}.biblio b ON b.biblionumber = bm.biblionumber 
    WHERE YEAR(b.datecreated) = '{year}'"""
r = pd.read_sql(query, db_conn)
r

   COUNT(bm.biblionumber)
0                    8318

### Notices créées dans l'année "à la main"

In [11]:
query = f"""SELECT COUNT(bm.biblionumber)
    FROM koha{year}.biblio_metadata bm
    JOIN koha{year}.biblio b ON b.biblionumber = bm.biblionumber 
    WHERE YEAR(b.datecreated) = '{year}'
    AND ExtractValue( bm.metadata, '//datafield[@tag="801"]/subfield[@code="b"]' ) = '595126101'"""
r = pd.read_sql(query, db_conn)
r

   COUNT(bm.biblionumber)
0                     219

### Nombre de notices entrées par importation dans l'année

In [12]:
# Nombre de notices entrées dans l'année - nombre de notices entrées à la main
query = f"""SELECT COUNT(bm.biblionumber)
    FROM koha{year}.biblio_metadata bm
    JOIN koha{year}.biblio b ON b.biblionumber = bm.biblionumber 
    WHERE YEAR(b.datecreated) = '{year}'
    AND ExtractValue( bm.metadata, '//datafield[@tag="801"]/subfield[@code="b"]' ) != '595126101'"""
r = pd.read_sql(query, db_conn)
r

   COUNT(bm.biblionumber)
0                    8099

## C3 - Locaux
|Intitulé|valeur|code SLL|
|:--|---|---|
|Surface utile nette totale (en m²)|5300|C301|
|Espaces de services Interns ( en m²)|590|C302|
|Espace de service public (en m²)|3350|C303|
|Espace manifestations et animations (en m²)|250|C304|
|Espace de magains|550|C305|
|Caféterias et surfaces détente|140|C306|
|Votre bâtiment est-il accessible au sens de la loi du 11 février 2005 ?|oui|C309|
|Précisez|Monte-personnes et ascenseurs qui permettent à chacun d'accéder à l'ensemble du bâtiment|C310|

# D - Collections

In [13]:
query = f"""SELECT
                    i.itemnumber,
                    i.barcode,
                    i.dateaccessioned,
                    i.price,
                    i.homebranch,
                    i.holdingbranch,
                    i.location,
                    i.ccode,
                    i.itemcallnumber,
                    i.notforloan,
                    i.damaged,
                    DATE(i.damaged_on),
                    i.withdrawn,
                    DATE(i.withdrawn_on),
                    i.itemlost,
                    DATE(i.itemlost_on),
                    i.onloan,
                    i.datelastborrowed,
                    i.biblionumber,
                    b.title as titre,
                    bi.publicationyear,
                    bi.itemtype,
                    i.timestamp
                FROM koha{year}.items i
                JOIN koha{year}.biblioitems bi ON i.biblionumber = bi.biblionumber
                JOIN koha{year}.biblio b ON i.biblionumber = b.biblionumber
                WHERE i.notforloan IN (-1, -2, 0, 2, -4, -3, 5)
                AND i.homebranch != 'MUS'"""
items = pd.read_sql(query, db_conn)

In [14]:
# On instancie la classe Document
# La classe Document permet d'ajouter les infos dont ont a besoin pour le SLL

exemplaires = Document(df=items, db_conn=db_conn)
exemplaires.get_doc_statdb_data()
exemplaires.get_doc_es_data()

In [15]:
exemplaires.df.columns

Index(['itemnumber', 'barcode', 'dateaccessioned', 'price', 'homebranch',
       'holdingbranch', 'location', 'ccode', 'itemcallnumber', 'notforloan',
       'damaged', 'DATE(i.damaged_on)', 'withdrawn', 'DATE(i.withdrawn_on)',
       'itemlost', 'DATE(i.itemlost_on)', 'onloan', 'datelastborrowed',
       'biblionumber', 'titre', 'publicationyear', 'itemtype', 'timestamp',
       'doc_item_id', 'doc_item_code_barre', 'doc_item_date_creation',
       'doc_item_prix', 'doc_item_site_detenteur_code',
       'doc_item_site_rattachement_code', 'doc_item_localisation_code',
       'doc_item_collection_ccode', 'doc_item_cote', 'doc_statut_code',
       'doc_statut_abime_code', 'doc_statut_desherbe_code',
       'doc_statut_perdu_code', 'doc_usage_emprunt_date',
       'doc_usage_date_dernier_pret', 'doc_biblio_id', 'doc_biblio_titre',
       'doc_biblio_annee_publication', 'doc_biblio_support_code',
       'doc_item_date_modif', 'doc_item_date_creation_annee',
       'doc_item_site_detenteur', 'doc_item_site_rattachement',
       'doc_item_localisation', 'doc_item_site_poldoc',
       'doc_item_collection_lib', 'doc_item_collection_lib1',
       'doc_item_collection_lib2', 'doc_item_collection_lib3',
       'doc_item_collection_lib4', 'doc_statut', 'doc_statut_abime',
       'doc_statut_desherbe', 'doc_statut_perdu', 'doc_usage_emprunt',
       'doc_usage_date_dernier_pret_annee', 'doc_biblio_support', 'sll_public',
       'sll_acces', 'sll_collection'],
      dtype='object')

In [16]:
exemplaires.df

,itemnumber,barcode,dateaccessioned,price,homebranch,holdingbranch,location,ccode,itemcallnumber,notforloan,...,doc_statut,doc_statut_abime,doc_statut_desherbe,doc_statut_perdu,doc_usage_emprunt,doc_usage_date_dernier_pret_annee,doc_biblio_support,sll_public,sll_acces,sll_collection
0,1,C0001353993,2005-03-22,8.99,MED,MED,MED0A,JABEFAE,EXT E C/ALE,0,...,3 - Empruntable,Non,Non,Non,non,2017.0,Livre,enfants,accès indirect,D1 - Livres imprimés
1,3,C0000653853,2005-03-22,8.99,MED,MED,MED0A,JABEFAE,EXT E C/ALE,0,...,3 - Empruntable,Non,Non,Non restitué,emprunté,2017.0,Livre,enfants,accès indirect,D1 - Livres imprimés
2,4,C0003476991,2005-03-22,1.00,MED,MED,MED0A,JABEFAE,EXT E C/ALE,0,...,3 - Empruntable,Non,Non,Non,non,2018.0,Livre,enfants,accès indirect,D1 - Livres imprimés
3,5,C0001499529,2005-03-22,8.99,MED,MED,MED0A,JABEFAE,EXT E C/ALE,0,...,3 - Empruntable,Non,Non,Non,non,2016.0,Livre,enfants,accès indirect,D1 - Livres imprimés
4,8,C0001353935,2005-03-22,8.99,MED,MED,MED0A,JABEFAE,EXT E C/ALE,0,...,3 - Empruntable,Non,Non,Non,non,2018.0,Livre,enfants,accès indirect,D1 - Livres imprimés
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261330,504863,None,2025-12-30,29.95,MED,MED,MED3A,ACFHSZZ,Doc./940.2 PAR,-2,...,2 - En traitement,Non,Non,Non,non,NaN,Livre,adultes,accès direct,D1 - Livres imprimés
261331,504864,C2500040372,2025-12-31,13.90,MED,MED,MED2A,JROROZZ,E R/CHI,0,...,3 - Empruntable,Non,Non,Non,non,NaN,Livre,enfants,accès direct,D1 - Livres imprimés
261332,504865,C2500040856,2025-12-31,15.90,MED,MED,MED1A,ALTROAD,ADO R/ELL,-2,...,2 - En traitement,Non,Non,Non,non,NaN,Livre,adultes,accès direct,D1 - Livres imprimés
261333,504866,C2500040857,2025-12-31,18.00,MED,MED,MED1A,ALTROAD,ADO R/RAZ,-2,...,2 - En traitement,Non,Non,Non,non,NaN,Livre,adultes,accès direct,D1 - Livres imprimés
261334,504867,C2500040859,2025-12-31,27.90,MED,MED,MED1A,ALTROAD,ADO R/FIT,-2,...,2 - En traitement,Non,Non,Non,non,NaN,Livre,adultes,accès direct,D1 - Livres imprimés

In [17]:
exemplaires.df['sll_acq'] = 'non'
exemplaires.df.loc[exemplaires.df['doc_item_date_creation'].astype('str').str[0:4] == '2023', 'sll_acq' ] = 'oui'

In [18]:
exemplaires_sll = exemplaires.df
exemplaires_sll = exemplaires_sll[['sll_acq', 'sll_public', 'sll_acces', 'sll_collection', 'doc_biblio_id', 'doc_item_id']]

In [19]:
exemplaires_sll['sll_public'].value_counts()

adultes    188601
enfants     72734
Name: sll_public, dtype: int64

In [20]:
exemplaires_sll['sll_acq'].value_counts()

non    248934
oui     12401
Name: sll_acq, dtype: int64

In [21]:
exemplaires_sll['sll_acces'].value_counts()

accès direct      134028
accès indirect    127307
Name: sll_acces, dtype: int64

In [22]:
query = f"""SELECT
                    itemnumber,
                    barcode,
                    dateaccessioned,
                    homebranch,
                    location,
                    ccode,
                    biblionumber,
                    itemtype
                FROM statdb.stat_eliminations
                WHERE annee_mise_pilon = '{year}'"""
elim = pd.read_sql(query, db_conn)

In [23]:
eliminations = Document(df=elim, db_conn=db_conn)
eliminations.get_doc_statdb_data()
eliminations.get_doc_es_data()

In [24]:
eliminations_sll = eliminations.df
eliminations_sll = eliminations_sll[['sll_public', 'sll_acces', 'sll_collection', 'doc_biblio_id', 'doc_item_id']]

## D1 - Livres imprimés

In [25]:
data = exemplaires_sll[exemplaires_sll['sll_collection'] == 'D1 - Livres imprimés']
data_el = eliminations_sll[eliminations_sll['sll_collection'] == 'D1 - Livres imprimés']

### Fonds
#### UM - Adultes et Enfants

In [26]:
data.groupby(['sll_public'])['doc_item_id'].nunique()

sll_public
adultes    122639
enfants     68506
Name: doc_item_id, dtype: int64

#### UM en libre-accès - Adultes et Enfants

In [27]:
data_libre_acces = data[data['sll_acces'] == 'accès direct']
data_libre_acces.groupby(['sll_public'])['doc_item_id'].nunique()

sll_public
adultes    62239
enfants    33709
Name: doc_item_id, dtype: int64

#### TITRES en libre accès - Adultes et Enfants

In [28]:
data_libre_acces = data[data['sll_acces'] == 'accès direct']
data_libre_acces.groupby(['sll_public'])['doc_biblio_id'].nunique()

sll_public
adultes    61079
enfants    29669
Name: doc_biblio_id, dtype: int64

### Acquisitions

#### Unités matérielles

In [29]:
data[data['sll_acq'] == 'oui'].groupby(['sll_public'])['doc_item_id'].nunique()

sll_public
adultes    5240
enfants    5328
Name: doc_item_id, dtype: int64

#### Titres

In [30]:
data[(data['sll_acq'] == 'oui')
     & (data['sll_acces'] == 'accès direct')].groupby(['sll_public'])['doc_biblio_id'].nunique()

sll_public
adultes    4122
enfants    3542
Name: doc_biblio_id, dtype: int64

### Eliminations

In [31]:
data_el.groupby(['sll_public'])['doc_item_id'].nunique()

sll_public
adultes    8486
enfants    4797
Name: doc_item_id, dtype: int64

###  TEST LUCAS

In [32]:
data.groupby(['sll_public'])['doc_item_id'].nunique()

sll_public
adultes    122639
enfants     68506
Name: doc_item_id, dtype: int64

In [33]:
import numpy as np
data_fonds = data.pivot_table(index=['sll_public','sll_acces'],
                             values=['doc_item_id','doc_biblio_id'],
                             aggfunc="nunique",
                             #margins=True,
                             #margins_name='Total'
                )
#data_fonds['total'] = data_fonds['doc_biblio_id'] + data_fonds['doc_item_id']

data_fonds_concat = pd.concat([
    y.append(y.sum().rename((x, 'Sous-Total')))
    for x, y in data_fonds.groupby(level=0)]).append(data_fonds.sum().rename(('Enfants + Adultes','Total')))
data_fonds_concat

/tmp/ipykernel_19144/2752056215.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y.append(y.sum().rename((x, 'Sous-Total')))
/tmp/ipykernel_19144/2752056215.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y.append(y.sum().rename((x, 'Sous-Total')))
/tmp/ipykernel_19144/2752056215.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_fonds_concat = pd.concat([

                                  doc_biblio_id  doc_item_id
sll_public        sll_acces
adultes           accès direct            61079        62239
                  accès indirect          57025        60400
                  Sous-Total             118104       122639
enfants           accès direct            29669        33709
                  accès indirect          25055        34797
                  Sous-Total              54724        68506
Enfants + Adultes Total                  172828       191145

In [34]:
exemplaires.df.columns

Index(['itemnumber', 'barcode', 'dateaccessioned', 'price', 'homebranch',
       'holdingbranch', 'location', 'ccode', 'itemcallnumber', 'notforloan',
       'damaged', 'DATE(i.damaged_on)', 'withdrawn', 'DATE(i.withdrawn_on)',
       'itemlost', 'DATE(i.itemlost_on)', 'onloan', 'datelastborrowed',
       'biblionumber', 'titre', 'publicationyear', 'itemtype', 'timestamp',
       'doc_item_id', 'doc_item_code_barre', 'doc_item_date_creation',
       'doc_item_prix', 'doc_item_site_detenteur_code',
       'doc_item_site_rattachement_code', 'doc_item_localisation_code',
       'doc_item_collection_ccode', 'doc_item_cote', 'doc_statut_code',
       'doc_statut_abime_code', 'doc_statut_desherbe_code',
       'doc_statut_perdu_code', 'doc_usage_emprunt_date',
       'doc_usage_date_dernier_pret', 'doc_biblio_id', 'doc_biblio_titre',
       'doc_biblio_annee_publication', 'doc_biblio_support_code',
       'doc_item_date_modif', 'doc_item_date_creation_annee',
       'doc_item_site_detenteur', 'doc_item_site_rattachement',
       'doc_item_localisation', 'doc_item_site_poldoc',
       'doc_item_collection_lib', 'doc_item_collection_lib1',
       'doc_item_collection_lib2', 'doc_item_collection_lib3',
       'doc_item_collection_lib4', 'doc_statut', 'doc_statut_abime',
       'doc_statut_desherbe', 'doc_statut_perdu', 'doc_usage_emprunt',
       'doc_usage_date_dernier_pret_annee', 'doc_biblio_support', 'sll_public',
       'sll_acces', 'sll_collection', 'sll_acq'],
      dtype='object')

## D2 - Publications en séries en cours imprmimées
> Demander à Stéphanie

query = f"""SELECT s.biblionumber,
s.startdate AS "debut_abonnement",
s.enddate AS "fin_abonnement",
b.title AS "titre", 
s.callnumber AS "cote",
s.location AS "localisation"
FROM koha_prod.subscription s 
LEFT JOIN biblio b on b.biblionumber = s.biblionumber
WHERE s.enddate >= '{year}-12-31'"""

abonnements_valides = pd.read_sql(query,db_conn)

loc_jeunesse = ['MED2A','MED2C']

abonnements_valides.loc[abonnements_valides['localisation'].isin(loc_jeunesse),
                        ['D2 - Abonnements']] = 'Jeunesse'

abonnements_valides.loc[~abonnements_valides['localisation'].isin(loc_jeunesse),
                        ['D2 - Abonnements']] = 'Adultes'

abonnements_valides['nb'] = 1

abonnements_valides.columns

abonnements_valides.pivot_table(index='D2 - Abonnements',
                                values=['nb','titre'],
                                aggfunc={
                                    'nb':sum,
                                    'titre':'nunique'
                                }
                               )

## D3 - Autres documents

###  Documents cartographiques

In [35]:
data = exemplaires_sll[exemplaires_sll['sll_collection'] == 'D3 – Documents cartographiques']

In [36]:
data['doc_item_id'].nunique()

81

In [37]:
data[data['sll_acq'] == 'oui']['doc_item_id'].nunique()

0

###  Musique imprimée

In [38]:
data = exemplaires_sll[exemplaires_sll['sll_collection'] == 'D3 – Musique imprimée']

In [39]:
data['doc_item_id'].nunique()

3016

In [40]:
data[data['sll_acq'] == 'oui']['doc_item_id'].nunique()

74

In [41]:
data[(data['sll_acces'] == 'accès direct')]['doc_item_id'].nunique()

1040

In [42]:
data[(data['sll_acces'] == 'accès direct')]['doc_biblio_id'].nunique()

1038

In [43]:
data[(data['sll_acces'] == 'accès direct') & (data['sll_acq'] == 'oui')]['doc_biblio_id'].nunique()

73

###  Documents graphiques

In [44]:
data = exemplaires_sll[exemplaires_sll['sll_collection'] == 'D3 - Documents graphiques']

In [45]:
data['doc_item_id'].nunique()

95

In [46]:
data[data['sll_acq'] == 'oui']['doc_item_id'].nunique()

1

###  Autres documents

In [47]:
data = exemplaires_sll[exemplaires_sll['sll_collection'] == 'D3 - Autres documents']

In [48]:
data['doc_item_id'].nunique()

143

In [49]:
data[data['sll_acq'] == 'oui']['doc_item_id'].nunique()

44

### Eliminations

In [50]:
data_el = eliminations_sll[eliminations_sll['sll_collection'].str[:2] == 'D3']
print(f"D320 - Total élimination Autres documents : {len(data_el)}")

D320 - Total élimination Autres documents : 190

## D4 - Documents audiovisuels sur support

In [51]:
exemplaires_sll['sll_collection'].value_counts()

D1 - Livres imprimés                                                                  191145
D4 - Documents audiovisuels fonds adultes / Documents sonores : musique                42845
D4 - Documents audiovisuels fonds adultes / documents vidéo adultes                    12153
D1 - Publications en série imprimées                                                    7610
D3 – Musique imprimée                                                                   3016
D4 - Documents audiovisuels fonds adultes / Documents sonores : livres enregistrés      1618
D4 - Documents audiovisuels fonds enfants / documents vidéo enfants                     1423
D4 - Documents audiovisuels fonds enfants / Documents sonores : musique                  680
D4 - Documents audiovisuels fonds enfants / Documents sonores : livres enregistrés       316
D4 - Total documents multimédia sur support                                              210
D3 - Autres documents                                                                    143
D3 - Documents graphiques                                                                 95
D3 – Documents cartographiques                                                            81
Name: sll_collection, dtype: int64

In [52]:
d4_coll = exemplaires_sll[exemplaires_sll['sll_collection'].str[:2] == 'D4']['sll_collection'].unique().tolist()

In [53]:
for c in d4_coll:
    print(c)
    print('-------------')
    data = exemplaires_sll[exemplaires_sll['sll_collection'] == c]
    data_el = eliminations_sll[eliminations_sll['sll_collection'] == c]
    print(f"fonds : {len(data)}")
    print(f"acquisitions : {len(data[data['sll_acq'] == 'oui'])}")
    print(f"eliminations : {len(data_el)}")
    
    print('-------------')

D4 - Documents audiovisuels fonds adultes / Documents sonores : musique
-------------
fonds : 42845
acquisitions : 601
eliminations : 2221
-------------
D4 - Documents audiovisuels fonds enfants / Documents sonores : musique
-------------
fonds : 680
acquisitions : 22
eliminations : 29
-------------
D4 - Documents audiovisuels fonds adultes / Documents sonores : livres enregistrés
-------------
fonds : 1618
acquisitions : 44
eliminations : 71
-------------
D4 - Documents audiovisuels fonds adultes / documents vidéo adultes
-------------
fonds : 12153
acquisitions : 365
eliminations : 628
-------------
D4 - Total documents multimédia sur support
-------------
fonds : 210
acquisitions : 1
eliminations : 8
-------------
D4 - Documents audiovisuels fonds enfants / Documents sonores : livres enregistrés
-------------
fonds : 316
acquisitions : 1
eliminations : 6
-------------
D4 - Documents audiovisuels fonds enfants / documents vidéo enfants
-------------
fonds : 1423
acquisitions : 92
eliminations : 53
-------------

In [54]:
data = exemplaires_sll[exemplaires_sll['sll_collection'] == 'D1 - Livres imprimés']
data_el = eliminations_sll[eliminations_sll['sll_collection'] == 'D1 - Livres imprimés']

## D6 - Ressources numériques acquises
> Depuis juin 2023 les ressources ne sont plus acquises directement par la médiathèque de Roubaix, mais par la MEL.

### Bouquets de contenus
Pour chaque item, merci de sélectionner le bouquet principal si vous en avez plusieurs
 
|Intitulé|oui/non|Nom de l'offre|Code SLL
|:---|:---:|---|---|
    |Livre|non|   |D522
|Livres enregistrés|non|   |D524
|Dictionnaires, encyclopédies|non|   |D526|
|Musique|non|   |D528
|Vidéo|non|   |D530|
|Presse|non|   |D532|
|Apprentissage en ligne (adultes)|non|   |D534|
|Ludo-éducatif (jeunesse)|non|   |D536|
|Autres bouquets acquis|non|   |D538

### Ressources à l'unité

|Intitulé|oui/non|Nombre d'acquisitions|Nom du fournisseur|Code SLL|
|:---|---|---|---|---|
|Livres|oui|45|Autre|D539-540-541|
|Presse|non|   |   |   |
Applications|non|   |   |   |
Autres ressources|non|   |   |    |

## D7 - Collections adaptées

|intitulé|oui/non|Code SLL|
|:---|---|---|
|La bibliothèque propose-t-elle des collections adaptées ?|oui|D701
|Livres en gros caractères|oui|D708
|Livres lus du commerce|oui|D709
|Braille|non|D702
|Ouvrages en Daisy|non|
|Revues en synthèse vocale|non|D703
|Revues en synthèse vocale|non|D704
|Livres-DVD en langue des signes française (LSF)|non|D705
|Livres tactiles ou en relief|non|D706
|Autres collections adaptées|oui|D707

# E - Usages et usagers de la bibliothèque

## E1 - Usagers

In [55]:
query = f"""SELECT
    date_extraction,
    age as adh_age,
    geo_ville as adh_geo_ville,
    geo_roubaix_iris as adh_geo_rbx_iris_code,
    sexe as adh_sexe,
    inscription_code_carte as adh_inscription_carte_code,
    inscription_code_site as adh_inscription_site_code,
    inscription_attribut as adh_inscription_attribut_action_code,
    inscription_fidelite as adh_inscription_nb_annees_adhesion,
    nb_venues_prets_mediatheque,
    nb_venues_prets_bus
FROM statdb.stat_adherents WHERE date_extraction = '{date_extraction_usagers}'"""
inscrits = pd.read_sql(query, db_conn)

In [56]:
adh = Adherent(df=inscrits, db_conn=db_conn)
adh.get_adherent_statdb_data()
adh.get_adherent_es_data()

In [57]:
adh.df['nb'] = 1
adh.df['adh_age_sll'] = 'Non pertinent'
adh.df.loc[adh.df['adh_age_lib3'] == '0 - 14 ans', 'adh_age_sll'] = '0 - 14 ans'
adh.df.loc[adh.df['adh_age_lib3'] == '15 - 24 ans', 'adh_age_sll'] = '15 - 64 ans'
adh.df.loc[adh.df['adh_age_lib3'] == '25 - 64 ans', 'adh_age_sll'] = '15 - 64 ans'
adh.df.loc[adh.df['adh_age_lib3'] == '65 ans et plus', 'adh_age_sll'] = '65 ans et plus'
adh.df.loc[adh.df['adh_age_lib3'] == 'Inconnu', 'adh_age_sll'] = 'Inconnu'

### Inscrits actifs

In [58]:
inscrits = adh.df

In [59]:
inscrits = inscrits[inscrits['adh_sexe'].isin(['M','F'])]

In [60]:
inscrits[inscrits['adh_age_sll']=="0 - 14 ans"].pivot_table(index='adh_age_sll',columns='adh_sexe',values='nb',
                 aggfunc=sum,margins=True,margins_name='total'
                ).rename(columns={'':'z/ vide',
                                  'M':'a/ Hommes',
                                  'F':'b/ Femmes',
                                  'N':'c/ Non pertinent',
                                  'O':'d/ Autre',
                                 })

adh_sexe     b/ Femmes  a/ Hommes  total
adh_age_sll
0 - 14 ans        2601       2385   4986
total             2601       2385   4986

In [61]:
inscrits[inscrits['adh_age_sll']!="0 - 14 ans"].pivot_table(index='adh_age_sll',columns='adh_sexe',values='nb',
                 aggfunc=sum,margins=True,margins_name='total'
                ).rename(columns={'':'z/ vide',
                                  'M':'a/ Hommes',
                                  'F':'b/ Femmes',
                                  'N':'c/ Non pertinent',
                                  'O':'d/ Autre',
                                 })

adh_sexe        b/ Femmes  a/ Hommes  total
adh_age_sll
15 - 64 ans          5590       3688   9278
65 ans et plus        531        423    954
total                6121       4111  10232

In [62]:
inscrits_TotalEnfantsAdultes = len(inscrits[inscrits['adh_age_sll']!="Non pertinent"])

inscrits_TotalEnfantsAdultesRoubaix = len(inscrits[(~inscrits["adh_age_sll"].isin(["Non pertinent"]))&
                                               (inscrits['adh_geo_ville']=="ROUBAIX")])

In [63]:
print(f"Total enfants et adultes : {inscrits_TotalEnfantsAdultes}")
print(f"    - Dont résidents dans la commune : {inscrits_TotalEnfantsAdultesRoubaix}")

Total enfants et adultes : 15218
    - Dont résidents dans la commune : 10640

### dont nouveaux inscrits

In [64]:
#nvx_inscrits = adh.df[adh.df['adh_inscription_nb_annees_adhesion'] == 0]
nvx_inscrits = inscrits[inscrits['adh_inscription_nb_annees_adhesion'] == 0]

In [65]:
nvx_inscrits[nvx_inscrits['adh_age_sll']=="0 - 14 ans"].pivot_table(index='adh_age_sll',columns='adh_sexe',values='nb',
                 aggfunc=sum,margins=True,margins_name='total'
                ).rename(columns={'':'e/ Vide',
                                  'M':'a/ Hommes',
                                  'F':'b/ Femmes',
                                  'N':'c/ Non pertinent',
                                  'O':'d/ Autres',
                                 })

adh_sexe     b/ Femmes  a/ Hommes  total
adh_age_sll
0 - 14 ans        1039        969   2008
total             1039        969   2008

In [66]:
nvx_inscrits[nvx_inscrits['adh_age_sll']!="0 - 14 ans"].pivot_table(index='adh_age_sll',columns='adh_sexe',values='nb',
                 aggfunc=sum,margins=True,margins_name='total'
                ).rename(columns={'':'e/ Vide',
                                  'M':'a/ Hommes',
                                  'F':'b/ Femmes',
                                  'N':'c/ Non pertinent',
                                  'O':'d/ Autres',
                                 })

adh_sexe        b/ Femmes  a/ Hommes  total
adh_age_sll
15 - 64 ans          2322       1532   3854
65 ans et plus         94         79    173
total                2416       1611   4027

In [67]:
nvx_inscrits_TotalEnfantsAdultes = len(nvx_inscrits[nvx_inscrits['adh_age_sll']!="Non pertinent"])

nvx_inscrits_TotalEnfantsAdultesRoubaix = len(nvx_inscrits[(~nvx_inscrits["adh_age_sll"].isin(["Non pertinent"]))&
                                               (nvx_inscrits['adh_geo_ville']=="ROUBAIX")])

In [68]:
print(f"Total enfants et adultes : {nvx_inscrits_TotalEnfantsAdultes}")
print(f"    - Dont résidents dans la commune : {nvx_inscrits_TotalEnfantsAdultesRoubaix}")

Total enfants et adultes : 6035
    - Dont résidents dans la commune : 4193

In [69]:
#nvx_inscrits['adh_inscription_carte_personnalite'].value_counts()

In [70]:
adh.df[adh.df['adh_inscription_nb_annees_adhesion']==0].groupby('adh_inscription_carte_personnalite').size()

adh_inscription_carte_personnalite
Collectivité      57
Personne        6040
dtype: int64

### Emprunteurs actifs

In [71]:
adh.df.columns

Index(['date_extraction', 'adh_age', 'adh_geo_ville', 'adh_geo_rbx_iris_code',
       'adh_sexe', 'adh_inscription_carte_code', 'adh_inscription_site_code',
       'adh_inscription_attribut_action_code',
       'adh_inscription_nb_annees_adhesion', 'nb_venues_prets_mediatheque',
       'nb_venues_prets_bus', 'adh_inscription_carte_personnalite_code',
       'adh_age_code', 'adh_age_lib1', 'adh_age_lib2', 'adh_age_lib3',
       'adh_geo_gentilite', 'adh_geo_rbx_iris', 'adh_geo_rbx_quartier',
       'geo_rbx_secteur', 'inscription_carte', 'adh_inscription_carte_type',
       'adh_inscription_carte_gratuite', 'adh_inscription_carte_prix',
       'adh_inscription_carte_personnalite', 'adh_inscription_site',
       'adh_inscription_nb_annees_adhesion_tra',
       'adh_inscription_attribut_action', 'nb', 'adh_age_sll'],
      dtype='object')

In [72]:
adh.df['emprunteur'] = 'non'
adh.df.loc[adh.df['nb_venues_prets_bus'] > 0, 'emprunteur'] = 'oui'
adh.df.loc[adh.df['nb_venues_prets_mediatheque'] > 0, 'emprunteur'] = 'oui'

data = adh.df[adh.df['emprunteur'] == 'oui']
len(data)

9805

In [73]:
data.groupby(['adh_age_sll', 'adh_sexe'])['nb'].sum()

adh_age_sll     adh_sexe
0 - 14 ans                     9
                F           2035
                M           1754
                O              1
15 - 64 ans                    9
                F           3301
                M           1689
                O              4
65 ans et plus  F            432
                M            278
Non pertinent   N            293
Name: nb, dtype: int64

In [74]:
data.groupby(['adh_age_sll'])['nb'].sum()

adh_age_sll
0 - 14 ans        3799
15 - 64 ans       5003
65 ans et plus     710
Non pertinent      293
Name: nb, dtype: int64

In [75]:
data.groupby(['adh_age_lib2', 'adh_sexe'])['nb'].sum()

adh_age_lib2    adh_sexe
15 ans et plus                 9
                F           3733
                M           1967
                O              4
<= 14 ans                      9
                F           2035
                M           1754
                O              1
Non pertinent   N            293
Name: nb, dtype: int64

In [76]:
data.groupby(['adh_age_lib2'])['nb'].sum()

adh_age_lib2
15 ans et plus    5713
<= 14 ans         3799
Non pertinent      293
Name: nb, dtype: int64

In [77]:
data[(data['adh_geo_ville'] == 'ROUBAIX') & (~adh.df['adh_age_sll'].isin(['Non pertinent', 'Inconnu']))]['nb'].sum()

/tmp/ipykernel_19144/3053756961.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[(data['adh_geo_ville'] == 'ROUBAIX') & (~adh.df['adh_age_sll'].isin(['Non pertinent', 'Inconnu']))]['nb'].sum()

6495

In [78]:

#data['adh_inscription_carte_personnalite'].value_counts()

### Fréquentation : entrées dans l'établissement

In [79]:
query = f"""SELECT
    SUM(entrees)
FROM statdb.stat_entrees WHERE YEAR(datetime) = '{year}'"""
entrees = pd.read_sql(query, db_conn)
entrees

   SUM(entrees)
0      275628.0

## E2 - Prêts

In [80]:
query = f"""SELECT
    issuedate as pret_date,
    date_due as pret_date_retour_prevue,
    returndate as pret_date_retour_effectif,
    renewals as pret_nb_renouvellement,
    branch as pret_site_pret_code,
    age as adh_age,
    sexe as adh_sexe_code,
    ville as adh_geo_ville,
    iris as adh_geo_rbx_iris_code,
    branchcode as adh_inscription_site_code,
    categorycode as adh_inscription_carte_code,
    fidelite as adh_inscription_nb_annees_adhesion,
    itemnumber as doc_item_id,
    homebranch as doc_item_site_detenteur_code,
    location as doc_item_localisation_code,
    ccode as doc_item_collection_ccode,
    itemcallnumber as doc_item_cote,
    itemtype as doc_biblio_support_code,
    publicationyear as doc_biblio_annee_publication,
    biblionumber as doc_biblio_id,
    dateaccessioned as doc_item_date_creation
FROM statdb.stat_issues
WHERE YEAR(issuedate) = '{year}'"""
prts = pd.read_sql(query, db_conn)
len(prts)

352264

In [81]:
c2l = Code2Libelle(db_conn)
c2l.get_val()
c2l = c2l.dict_codes_lib

prets = Pret(df=prts, db_conn=db_conn, c2l=c2l)
prets.get_pret_statdb_data()
prets.get_pret_es_data()

In [82]:
prets_sll = prets.df[['sll_public', 'sll_acces', 'sll_prets_coll', 'sll_collection', 'sll_prets']]
prets_sll['nb'] = 1

/tmp/ipykernel_19144/3051755607.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prets_sll['nb'] = 1

In [83]:
# Nb de prêts - hors Collectivités
data = prets_sll.pivot_table(index="sll_prets",
                             columns="sll_public",
                             values="nb",
                             aggfunc=sum,
                             margins=True,
                             margins_name='Total')
data

sll_public                            adultes  enfants   Total
sll_prets
Autres documents                         1075       60    1135
E2 - Documents vidéo                    16115     3735   19850
E2 - Livres                            102333   200182  302515
E2 – Documents sonores : livres          1401      366    1767
E2 – Documents sonores : musique         9550      444    9994
E2 – Publications en série imprimées    11989     5014   17003
Total                                  142463   209801  352264

In [84]:
# Nb de prêts - Collectivités
data_coll = prets_sll[prets_sll['sll_prets_coll']=="Prêt aux collectivités"].pivot_table(index="sll_prets",
                                                                                         #columns="sll_public",
                                                                                         values="nb",
                                                                                         aggfunc=sum,
                                                                                         margins=True,
                                                                                         margins_name='Total').rename(columns={"nb":"Dont Collectivités"})
data_coll

                                      Dont Collectivités
sll_prets
Autres documents                                      55
E2 - Documents vidéo                                  75
E2 - Livres                                        30832
E2 – Documents sonores : livres                       31
E2 – Documents sonores : musique                      17
E2 – Publications en série imprimées                  40
Total                                              31050

In [85]:
data_synthese = data.merge(data_coll,
                           left_on='sll_prets',
                           right_on='sll_prets',
                           how='left'
                          )
data_synthese = data_synthese[["adultes",'enfants','Total','Dont Collectivités']]

In [86]:
lst = ["E2 - Livres",
       "E2 – Publications en série imprimées",
       "E2 – Documents sonores : musique",
       "E2 – Documents sonores : livres",
       "E2 - Documents vidéo",
       "Autres documents",
       "Total"
      ]
data_synthese.loc[lst]

,adultes,enfants,Total,Dont Collectivités
sll_prets,,,,
E2 - Livres,102333,200182,302515,30832
E2 – Publications en série imprimées,11989,5014,17003,40
E2 – Documents sonores : musique,9550,444,9994,17
E2 – Documents sonores : livres,1401,366,1767,31
E2 - Documents vidéo,16115,3735,19850,75
Autres documents,1075,60,1135,55
Total,142463,209801,352264,31050

> A la dernière ligne **Tota** il faut ajouter pour valeur le **Nb de prêts de livres numériques**. Ce chiffre est à récupérer auprès de Mathilde L.

## E3 - Autres types d'usages

### Réservations

In [87]:
query = f"""SELECT
    COUNT(*)
FROM statdb.stat_reserves WHERE YEAR(reservedate) = '{year}'"""
r = pd.read_sql(query, db_conn)
r

   COUNT(*)
0     55532

## E5 - Sessions internet (connexions + wifi)

In [88]:
query = f"""SELECT
    COUNT(*)
FROM statdb.stat_webkiosk WHERE YEAR(heure_deb) = '{year}'"""
r = pd.read_sql(query, db_conn)
r

   COUNT(*)
0     61801

In [89]:
query = f"""SELECT
    COUNT(*)
FROM statdb.stat_wifi WHERE YEAR(start_wifi) = '{year}'"""
r = pd.read_sql(query, db_conn)
r

   COUNT(*)
0     11739

### E502 - Nombre de visites du site dans la bibliothèque (visite interne)

In [90]:
query = f"""SELECT SUM(visites) AS 'Total visites interne'
FROM statdb.stat_web2 sw 
WHERE YEAR(`date`) = {year}
AND origine = 'interne'"""

pd.read_sql(query,db_conn)

   Total visites interne
0                13715.0

### E503 - Nombre de visite du site internet hors bibliothèque (visite externe)

In [91]:
query = f"""SELECT SUM(visites) AS 'Total visites externe'
FROM statdb.stat_web2 sw 
WHERE YEAR(`date`) = {year}
AND origine = 'externe'"""

pd.read_sql(query,db_conn)

   Total visites externe
0               188487.0

# H - Action culturelle (nouvelle version)

* [ ] Mettre à jour le script suite à la modif du tableau source
* [ ] Vérifier les étapes stats
* [ ] Créer une classe en Python pour gérer les stats sll & stats pour collègues

> ***NOTE : avant de lancer le scrip***   
    1. Récupérer la version la plus récente du fichier `tableaux_suivi_AECS`  
    2. Importer le fichier dans le répertoire `/home/kibini/kibini2/kibini/data/aecs`  
    3. Ajouter la date d'import dans kibini a la fin du nom du fichier. 
    Exemple : `tableaux_suivi_AECS_20250917`

In [118]:
#from kiblib.utils.aecs import AECS

In [1]:
import string
import pandas as pd
import numpy as np
import seaborn as sns
import re
from datetime import datetime as dt
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings("ignore")

class AECS():
    def __init__(self,set_sll_columns=False):    
        sheets2keep = ['Baptiste','Bruno',
                       'Céline','Esther',
                       'Gwen','Hélène',
                       'Inès','Laetitia C',
                       'Laetitia D','Mathilde M',
                       'Pascale','Zina'
                      ]
                      
        alphabet = list(string.ascii_lowercase)
        data_date = '20260423'
        filepath_data = f'../data/aecs/tableaux_suivi_AECS_{data_date}.xlsx'
        
        self.aecs = pd.read_excel(filepath_data,sheet_name=sheets2keep)
        self.aecs = pd.concat(self.aecs)
        self.aecs = self.aecs.droplevel(level=1).reset_index()          
        self.aecs['Nb actions'] = 1
        
        #On supprime la braderie qui fausse les stats
        self.aecs = self.aecs[~self.aecs["Nom action ou projet"].fillna('(vide)').str.contains("braderie",case=False)]
        
        #Transformation des datetime en objet date propre / Format YYYY-MM-DD
        self.aecs['Date début action'] = pd.to_datetime(self.aecs['Date début action']).dt.date
        
        self.aecs['Date début action'] = self.aecs['Date début action'].astype(str)
        
        # Pour toutes les feuilles
        
        # Si au moins une des 2 colonnes remplies => Total Personnes touchées = Total Enfant + Total Adulte
        self.aecs.loc[(~self.aecs["Estimation Total Enfants touchés"].isna()) |
                      (~self.aecs["Estimation Total Adultes touchés"].isna()),"Estimation Total Personnes touchées"] = self.aecs["Estimation Total Enfants touchés"] + self.aecs["Estimation Total Adultes touchés"]
        
        
        #Pour Action Culturelle uniquement on copie dans la colonne "Total" les données de la colonne"Estimation Total Personnes touchées"
        self.aecs.loc[self.aecs['index']=="Mathilde M","Estimation Total Personnes touchées"] = self.aecs['Estimation Total Personnes touchées']
        
        self.aecs_collectivites = self.aecs[self.aecs["index"]=='Laetitia D']
        self.effectifs_scolaires = pd.read_excel(filepath_data,sheet_name='Effectifs')
        self.aecs_collectivites = self.aecs_collectivites.merge(self.effectifs_scolaires,left_on="Nom d'équipement",right_on="Nom",how='left')
        self.list_SchoolNames = list(self.aecs_collectivites[self.aecs_collectivites['Type de structure']=="Ecole"]["Nom d'équipement"].unique())
        
        #self.aecs = self.aecs[self.aecs["index"]=='Mathilde M']
        #self.aes = self.aecs[self.aecs["index"]!='Mathilde M']
        

        if set_sll_columns==True:
            
            #H3
            self.aecs.loc[(self.aecs["Champ d'action"]=="Culture") |
                          (self.aecs["Champ d'action"]==" dont Livre et lecture"),
                          "H3 - Structures associatives"] = "a/ Culture"
            
            self.aecs.loc[self.aecs["Champ d'action"]==" dont Livre et lecture","H3 - Structures associatives"] = "b/  dont Livre et lecture publique"
            
            self.aecs.loc[(self.aecs["Champ d'action"]!="Culture") &
                          (self.aecs["Champ d'action"]!=" dont Livre et lecture"),
                          "H3 - Structures associatives"] = "c/ Autres"
            
            # H4 - Ajout colonnes pour action culturelle
            # Propositions en libre accès
            # Ateliers participatifs
            
            # Médiation numérique
            # Escape Game
            # Formation tout au long de la vie
            
            #Médiation Numérique
            self.aecs.loc[self.aecs["Type d'action"]=="Atelier informatique","H4 - Actions au sein de l'établissement"] = "Médiation numérique"
            
            # Jeux de société sur place
            self.aecs.loc[self.aecs["Type d'action"]=="Jeux","H4 - Actions au sein de l'établissement"] = "Jeux de société sur place"
            
            
            # Expositions
            self.aecs.loc[self.aecs["Type d'action"]=="Exposition","H4 - Actions au sein de l'établissement"] = "Expositions"
            
            # Fêtes, salons du livre, festivals
            self.aecs.loc[(self.aecs["Type d'action"].isin(["Journée festive","Salon du livre","Festival"])) &
                        (self.aecs["Evenement"].notna()),
                        "H4 - Actions au sein de l'établissement"] = "Fêtes, salons du livre, festivals" 
            
            # Spectacles
            self.aecs.loc[self.aecs["Type d'action"]=="Spectacle",
                        "H4 - Actions au sein de l'établissement"] = "Spectacles"
                        
            
            # Conférences rencontres lectures
            self.aecs.loc[(self.aecs["Type d'action"]=="Conférence") |
                        (self.aecs["Type d'action"]=="Rencontre") |
                        (self.aecs["Type d'action"]=="Lecture"),
                       "H4 - Actions au sein de l'établissement"] = "Conférences, rencontres, lectures"
            
            # Séances de conte
            self.aecs.loc[self.aecs["Type d'action"]=="Séance de contes",
                        "H4 - Actions au sein de l'établissement"] = "Séances de contes"
            
            
            # Concert
            self.aecs.loc[self.aecs["Type d'action"]=="Concert",
                        "H4 - Actions au sein de l'établissement"] = "Concerts"
            
            # Projection
            self.aecs.loc[self.aecs["Type d'action"]=="Projection",
                        "H4 - Actions au sein de l'établissement"] = "Projections"
            

            # Clubs de lecteurs
            self.aecs.loc[self.aecs["Type d'action"]=="Club lecture",
                        "H4 - Actions au sein de l'établissement"] = "Clubs de lecteurs"

            # Ateliers d'écriture
            self.aecs.loc[self.aecs["Type d'action"]=="Atelier d'écriture",
                        "H4 - Actions au sein de l'établissement"] = "Ateliers d'écriture"
            
                
            # Jeux vidéo sur place
            self.aecs.loc[self.aecs["Type d'action"]=="Jeux-vidéo",
                        "H4 - Actions au sein de l'établissement"] = "Jeux-vidéos sur place"
            
            # Ateliers
            self.aecs.loc[self.aecs["Type d'action"]=="Atelier",
                        "H4 - Actions au sein de l'établissement"] = "Ateliers"
            
            # Autres
            list_type_actions = ["Expositions",
                                 "Fêtes, salons du livre, festivals",
                                 "Spectacles",
                                 "Conférences, rencontres, lectures",
                                 "Séances de contes",
                                 "Concerts",
                                 "Projections",
                                 "Clubs de lecteurs",
                                 "Ateliers d'écriture",
                                 "Jeux-vidéos sur place",
                                 "Ateliers",
                                 "Jeux de société sur place",
                                 "Médiation numérique"
                                 
                                ]
            
            self.aecs.loc[~self.aecs["H4 - Actions au sein de l'établissement"].isin(list_type_actions),
                        "H4 - Actions au sein de l'établissement"] = "Autres"
            
            self.aecs.loc[self.aecs["Type de public"].isin(['Enfants','Petite enfance','Adolescents']),'sll_type_public'] = 'a/ Enfants'
            self.aecs.loc[~self.aecs['Type de public'].isin(['Enfants','Petite enfance','Adolescents']),'sll_type_public'] = 'b/ Tout public'
            
            # Création d'un dictionnaire
            dict_TypeDeStructure = {'Ecole':'Écoles',
                                    'Collège':'Collèges',
                                    'Lycée':'Lycées',
                                    'Supérieur':'Supérieur',
                                    'Maison_de_retraite':'Maisons de retraite',
                                    'Centre_social':'Centres sociaux',
                                    'Centre_de_loisirs':'Centres de loisirs',
                                    'Structure_de_la_petite_enfance':'Services de la petite enfance',
                                    'Service_emploi_et_formation':'Services de l\'emploi',
                                    'Equipement_medicosocial':'Équipements médico-sociaux'}
            
            # Création d'une liste de clés et de valeurs
            keys = dict_TypeDeStructure.keys()
            values = dict_TypeDeStructure.values()
            column_to_parse = 'Type de structure'
            column_to_add = 'H1 - Partenariats avec des institutions'
            
            # Pour chaque paire clé/valeurs, 
            # si Type de structure contient clé
            # Pour nouvelle colonne H1 - Partenariat avec les institutions, utilisé valeurs associée
            for key,value,letter in zip(keys,values,alphabet):
                self.aecs.loc[self.aecs[column_to_parse]==key,column_to_add] = f'{letter}/ {value}'

        
            dict_TypeDePublic = {"Personnes âgées (65 ans et plus)":"Personnes âgées",
            "Personnes en situation de handicap":"Personnes en situation de hancidap",
            "Jeunes (18-25 ans)":"Jeunes",
            "Personnes en recherche d'emploi":"Personnes en recherche d'emploi",
            "Personnes en situation d'illettrisme":"Personnes en situation d'illétrisme",
            "Populations allophones":"Population non-francophone",
            "Populations en situation d'insertion sociale":"Population en situation d'insertion sociale"}

            keys = dict_TypeDePublic.keys()
            values = dict_TypeDePublic.values()
            for key,value,letter in zip(keys,values,alphabet):
                self.aecs.loc[self.aecs["Type de public"]==key,
                             'H7 - Actions et services à destination de publics à besoins spécifiques'] = f'{letter}/ {value}'

    
    def get_SLL_datas(self):        
        self.get_SLL_H1_PartenariatsAvecDesInstitutions()
        self.get_SLL_H2_PartenariatsAvecDesEquipementsCulturels()
        self.get_SLL_H3_PartenariatsAvecDesAssociations()
        self.get_SLL_H4_ActionsAuSeinDelEtablissement()
        self.get_SLL_H5_ActionsHorsDelEtablissement()
        self.get_SLL_H7_PublicsSpecifiques()
        
   
    def get_SLL_PeriodeScolaire(self,date_debut,date_fin):
    
        self.aecs = self.aecs[(self.aecs['Date début action']>=date_debut)&
                              (self.aecs['Date début action']<=date_fin)
                             ]
    
    def get_SLL_H1_PartenariatsAvecDesInstitutions(self):
        
        self.aecs_H1XX_df = self.aecs.pivot_table(index='H1 - Partenariats avec des institutions',
                                                  values=["Nb de classes touchées si public scolaire",
                                                          "Nb d'accueil ou séance",
                                                          "Estimation Total Personnes touchées"],
                                                  aggfunc=sum)[["Nb de classes touchées si public scolaire",
                                                                "Nb d'accueil ou séance",
                                                                "Estimation Total Personnes touchées"]]
                                         
        
        #self.aecs_H1XX_df = self.aecs.groupby('H1 - Partenariats avec des institutions')['Estimation Total Personnes touchées'].sum().to_frame()
        return(self.aecs_H1XX_df)

        
        
    def get_SLL_H2_PartenariatsAvecDesEquipementsCulturels(self):
        
        
        self.aecs_H2XX_df = self.aecs[self.aecs["Type de structure"]=="Centre_culturel"].groupby("Nom d'équipement")['Estimation Total Personnes touchées'].sum().to_frame()
        return(self.aecs_H2XX_df)
    
    
    def get_SLL_H3_PartenariatsAvecDesAssociations(self):
        
        self.aecs_H304_307 = self.aecs[self.aecs["En partenariat avec"]=="Structure_associative"]
        self.aecs_H304_307 = self.aecs_H304_307.groupby("H3 - Structures associatives")["Nom d'équipement"].nunique()
        
    def get_SLL_H4_ActionsAuSeinDelEtablissement(self):
        self.ac = self.aecs[self.aecs["index"]=="Mathilde M"]
        self.ac_H4XX_df_PopulationTouchee = pd.pivot_table(data=self.ac,index="H4 - Actions au sein de l'établissement",
                                           columns="sll_type_public",
                                           values="Estimation Total Personnes touchées",
                                           aggfunc=sum,
                                           margins=True,
                                           dropna=False,
                                           margins_name="Total"
                                          )[["b/ Tout public","a/ Enfants","Total"]]
        
        self.ac_H4XX_df_NbActions = pd.pivot_table(data=self.ac,index="H4 - Actions au sein de l'établissement",
                                           columns="sll_type_public",
                                           values="Nb actions",
                                           aggfunc=sum,
                                           margins=True,
                                           dropna=False,
                                           margins_name="Total"
                                          )[["b/ Tout public","a/ Enfants","Total"]]
        
        self.ac_H4XX_df_Synthese = pd.pivot_table(data=self.ac,index="H4 - Actions au sein de l'établissement",
                                           columns="sll_type_public",
                                           values=["Nb actions","Estimation Total Personnes touchées"],
                                           aggfunc=sum,
                                           margins=True,
                                           dropna=False,
                                           margins_name="Total"
                                          )
    
    def get_SLL_H5_ActionsHorsDelEtablissement(self,print_result=False):
        
        self.aecs_H5XX_df_HorsLesMurs = self.aecs[(self.aecs['Lieu']=='Hors les murs') &
                                                  (self.aecs['index']!='Laetitia D')]
        
        self.aecs_H5XX_NbActionsHorsLesMursMed = self.aecs_H5XX_df_HorsLesMurs['Nb actions'].sum()
        self.aecs_H5XX_NbActionsHorsLesMursCol = len(self.aecs_collectivites)
        self.aecs_H502_NbActionsHorsLesMurs = self.aecs_H5XX_NbActionsHorsLesMursCol + self.aecs_H5XX_NbActionsHorsLesMursMed
            
        
        for name in self.list_SchoolNames:
            aecs_collectivites_school = self.aecs_collectivites[self.aecs_collectivites["Nom d'équipement"]==name]
            Total_actions_BCD = len(aecs_collectivites_school[aecs_collectivites_school["Nom action ou projet"]=="BCD"])
            Total_actions_MARM = len(aecs_collectivites_school[aecs_collectivites_school["Nom action ou projet"]=="MARMOTHEQUE"])
            Total_emprunteurs_distincts = aecs_collectivites_school["Nom emprunteur"].nunique()
            self.aecs_collectivites.loc[self.aecs_collectivites["Nom d'équipement"]==name,'Total_actions_BCD']=Total_actions_BCD
            self.aecs_collectivites.loc[self.aecs_collectivites["Nom d'équipement"]==name,'Total_actions_Marmothèque'] = Total_actions_MARM
            self.aecs_collectivites.loc[self.aecs_collectivites["Nom d'équipement"]==name,'Total_emprunteurs_distincts'] = Total_emprunteurs_distincts
            
        effectif_moyen_classe = 25    
        self.aecs_collectivites.loc[self.aecs_collectivites["Total_actions_BCD"]>0,'Estimation Total Enfants touchés'] = self.aecs_collectivites['Total Ecole']
        self.aecs_collectivites.loc[self.aecs_collectivites["Total_actions_Marmothèque"]>0,'Estimation Total Enfants touchés'] = self.aecs_collectivites['Total Maternelle']
        self.aecs_collectivites.loc[
            (self.aecs_collectivites["Total_actions_BCD"]==0) &
            (self.aecs_collectivites["Total_actions_Marmothèque"]==0),'Estimation Total Enfants touchés'] = self.aecs_collectivites['Total_emprunteurs_distincts'] * effectif_moyen_classe

        # Suppression des noms doublons pour les noms d'école
        self.aecs_collectivites.drop_duplicates(subset="Nom",
                                                inplace=True)
        
        self.aecs_collectivites_schools = self.aecs_collectivites[["index","Nom","Estimation Total Enfants touchés"]]
        
        self.aecs_H5XX_PopulationToucheeCol = self.aecs_collectivites_schools["Estimation Total Enfants touchés"].sum()
        self.aecs_H5XX_PopulationToucheeMed = self.aecs_H5XX_df_HorsLesMurs['Estimation Total Personnes touchées'].sum()
        self.aecs_H503_PopulationTouchee = self.aecs_H5XX_NbActionsHorsLesMursMed + self.aecs_H5XX_PopulationToucheeCol
        
        
    def get_SLL_H7_PublicsSpecifiques(self):
        
        self.aecs_H7XX_df = self.aecs.groupby('H7 - Actions et services à destination de publics à besoins spécifiques')['Nb actions','Estimation Total Personnes touchées'].sum()
        return(self.aecs_H7XX_df)
        
    def get_Statistiques(self,print_result=False,filter_on=None,method = None,group_by_what = [],total_on = [],count_actions_numbers=False):
        
        if filter_on == 'ac':
            self.stats = self.df[self.df.index.get_level_values(0)=='Mathilde M'] # On ne garde que le feuille Excel de Mathilde
            
        if filter_on == 'aecs':
            self.stats = self.df[self.df.index.get_level_values(0)!='Mathilde M'] # On exclut la feuille Excel de Mathilde
        
        self.stats['Date début action'] = pd.to_datetime(self.stats['Date début action'],
                                                         errors='coerce',
                                                         format='%Y-%m-%d %H:%M:%S')
        
        self.stats['annee'] = pd.DatetimeIndex(self.stats['Date début action']).year
        
            
        self.stats = self.stats.groupby(group_by_what)[total_on].sum()
        return(self.stats)

In [2]:
sll = AECS(set_sll_columns=True)

In [3]:
sll.get_SLL_PeriodeScolaire(date_debut='2024-09-31',date_fin='2025-08-31')
sll.get_SLL_datas()

# H1 - Etablissement scolaire et universitaire

In [4]:
sll.aecs_H1XX_df

,Nb de classes touchées si public scolaire,Nb d'accueil ou séance,Estimation Total Personnes touchées
H1 - Partenariats avec des institutions,,,
a/ Écoles,129.0,242.0,2297.0
b/ Collèges,34.0,28.0,291.0
c/ Lycées,10.0,15.0,78.0
d/ Supérieur,0.0,4.0,163.0
e/ Maisons de retraite,0.0,4.0,43.0
f/ Centres sociaux,15.0,49.0,538.0
g/ Centres de loisirs,3.0,3.0,14.0
h/ Services de la petite enfance,0.0,3.0,57.0
i/ Services de l'emploi,0.0,13.0,121.0

# H2 - Équipements culturels

In [5]:
sll.aecs_H2XX_df

                                                 Estimation Total Personnes touchées
Nom d'équipement
Archives Nationales du Monde du Travail Roubaix                                 15.0
Autres                                                                          38.0

# H3 - Structures associatives

In [6]:
sll.aecs_H304_307

H3 - Structures associatives
a/ Culture                            13
b/  dont Livre et lecture publique     2
c/ Autres                              1
Name: Nom d'équipement, dtype: int64

# H4 - Actions au sein de l'établissement

In [7]:
sll.ac_H4XX_df_NbActions

sll_type_public                          b/ Tout public  a/ Enfants  Total
H4 - Actions au sein de l'établissement
Ateliers                                           49.0         3.0     52
Ateliers d'écriture                                 6.0         1.0      7
Autres                                              4.0         NaN      4
Clubs de lecteurs                                   6.0         NaN      6
Concerts                                            7.0         6.0     13
Conférences, rencontres, lectures                  50.0       109.0    159
Expositions                                         9.0         NaN      9
Jeux de société sur place                           9.0         NaN      9
Jeux-vidéos sur place                              17.0         8.0     25
Médiation numérique                                 5.0         2.0      7
Projections                                         6.0         3.0      9
Spectacles                                          6.0         4.0     10
Séances de contes                                   NaN         6.0      6
Total                                             174.0       142.0    316

In [8]:
sll.ac_H4XX_df_PopulationTouchee

sll_type_public                          b/ Tout public  a/ Enfants   Total
H4 - Actions au sein de l'établissement
Ateliers                                          888.0        29.0   917.0
Ateliers d'écriture                                93.0         0.0    93.0
Autres                                            174.0         NaN   174.0
Clubs de lecteurs                                  83.0         NaN    83.0
Concerts                                          335.0       357.0   692.0
Conférences, rencontres, lectures                1264.0      3620.0  4884.0
Expositions                                       504.0         NaN   504.0
Jeux de société sur place                         164.0         NaN   164.0
Jeux-vidéos sur place                             583.0       245.0   828.0
Médiation numérique                                33.0        13.0    46.0
Projections                                       149.0       226.0   375.0
Spectacles                                        370.0       210.0   580.0
Séances de contes                                   NaN       143.0   143.0
Total                                            4640.0      4843.0     NaN

In [9]:
sll.ac_H4XX_df_Synthese

                                        Estimation Total Personnes touchées  \
sll_type_public                                                  a/ Enfants
H4 - Actions au sein de l'établissement
Ateliers                                                               29.0
Ateliers d'écriture                                                     0.0
Autres                                                                  NaN
Clubs de lecteurs                                                       NaN
Concerts                                                              357.0
Conférences, rencontres, lectures                                    3620.0
Expositions                                                             NaN
Jeux de société sur place                                               NaN
Jeux-vidéos sur place                                                 245.0
Médiation numérique                                                    13.0
Projections                                                           226.0
Spectacles                                                            210.0
Séances de contes                                                     143.0
Total                                                                4843.0

                                                               Nb actions  \
sll_type_public                         b/ Tout public   Total a/ Enfants
H4 - Actions au sein de l'établissement
Ateliers                                         888.0   917.0        3.0
Ateliers d'écriture                               93.0    93.0        1.0
Autres                                           174.0   174.0        NaN
Clubs de lecteurs                                 83.0    83.0        NaN
Concerts                                         335.0   692.0        6.0
Conférences, rencontres, lectures               1264.0  4884.0      109.0
Expositions                                      504.0   504.0        NaN
Jeux de société sur place                        164.0   164.0        NaN
Jeux-vidéos sur place                            583.0   828.0        8.0
Médiation numérique                               33.0    46.0        2.0
Projections                                      149.0   375.0        3.0
Spectacles                                       370.0   580.0        4.0
Séances de contes                                  NaN   143.0        6.0
Total                                           4640.0     NaN      142.0


sll_type_public                         b/ Tout public Total
H4 - Actions au sein de l'établissement
Ateliers                                          49.0    52
Ateliers d'écriture                                6.0     7
Autres                                             4.0     4
Clubs de lecteurs                                  6.0     6
Concerts                                           7.0    13
Conférences, rencontres, lectures                 50.0   159
Expositions                                        9.0     9
Jeux de société sur place                          9.0     9
Jeux-vidéos sur place                             17.0    25
Médiation numérique                                5.0     7
Projections                                        6.0     9
Spectacles                                         6.0    10
Séances de contes                                  NaN     6
Total                                            174.0   316

# H5 - Actions hors de l'établissement

In [10]:
print(f"H501 - Actions hor de l'établissement : OUI")
print(f"H502 - Nb action hors les murs : {sll.aecs_H502_NbActionsHorsLesMurs}")
print(f"H503 - Population touchée : {sll.aecs_H503_PopulationTouchee}")
print(f"H504 - Nb de prêts à domicile : Demander au service de prêts à domicile")

H501 - Actions hor de l'établissement : OUI
H502 - Nb action hors les murs : 2723
H503 - Population touchée : 8029.0
H504 - Nb de prêts à domicile : Demander au service de prêts à domicile

# H6 - Actions de coopération


|Intitulé|Oui/Non?|Champ|
|:---|---|---|
|Coopération locale|Oui|H601
|- Dont dont actions de coopération intercommunale (avec des bibliothèques n’appartenant pas à votre collectivité)|Oui|H610|
|Catalogue commun|Oui|H612|
|Portail documentaire commun|Non|H613|
|Politique documentaire commune|Non|H613
|Navette documentaire|Non|H614
|Carte unique de lecteur|Non|H615
|Action culturelle commune|Oui|H617
|Autre action de coopération intercommunal|Non|H616
|Coopération nationale|Oui|H604
|Nombre d'actions|4|H605
|Coopération internationale|Non|H607

# H7 Actions et services à destination de publics à besoins spécifiques

In [48]:
sll.aecs_H7XX_df

Empty DataFrame
Columns: [Nb actions, Estimation Total Personnes touchées]
Index: []

# K - Patrimoine

## K2 - Fonds et acquisitions

In [128]:
query = f"""SELECT
                    i.itemnumber,
                    i.barcode,
                    i.dateaccessioned,
                    i.price,
                    i.homebranch,
                    i.holdingbranch,
                    i.location,
                    i.ccode,
                    i.itemcallnumber,
                    i.notforloan,
                    i.damaged,
                    DATE(i.damaged_on),
                    i.withdrawn,
                    DATE(i.withdrawn_on),
                    i.itemlost,
                    DATE(i.itemlost_on),
                    i.onloan,
                    i.datelastborrowed,
                    i.biblionumber,
                    b.title as titre,
                    bi.publicationyear,
                    bi.itemtype,
                    i.timestamp
                FROM koha{year}.items i
                JOIN koha{year}.biblioitems bi ON i.biblionumber = bi.biblionumber
                JOIN koha{year}.biblio b ON i.biblionumber = b.biblionumber
                WHERE i.notforloan IN (-1, -2, 0, 2, -4, 5)
                AND i.homebranch != 'MUS'"""
items = pd.read_sql(query, db_conn)

In [129]:
exemplaires = Document(df=items, db_conn=db_conn)
exemplaires.get_doc_statdb_data()
exemplaires.get_doc_es_data()

In [130]:
pat_ccode = ['PENACZZ', 'PENCVZZ', 'PENDEZZ', 'PENHPZZ', 'PENPDZZ', 'PENRSZZ', 'AAPPRLP',
             'PPAFIZZ', 'PPEFGZZ', 'PPELGZZ', 'PPEPMZZ', 'PPEPRZZ', 'PPIPIZZ', 'P17']
patrimoine_df = exemplaires.df[exemplaires.df['doc_item_collection_ccode'].isin(pat_ccode)]
patrimoine_df['sll_acq'] = 'non'
patrimoine_df.loc[patrimoine_df['doc_item_date_creation'].astype('str').str[0:4] == str(year), 'sll_acq' ] = 'oui'

In [131]:
len(patrimoine_df)

63291

### Livres imprimés

In [132]:
data = patrimoine_df[patrimoine_df['sll_collection'] == 'D1 - Livres imprimés']

In [107]:
print(f"fonds : {len(data)}")

fonds : 36081

In [108]:
print(f"acquisitions : {len(data[data['sll_acq'] == 'oui'])}")

acquisitions : 157

In [109]:
print(f"dont livres d'artistes : fonds : {len(patrimoine_df[patrimoine_df['doc_item_collection_ccode'] == 'AAPPRLP'])}")

dont livres d'artistes : fonds : 546

In [110]:
print(f"dont livres d'artistes : acquisitions : {len(patrimoine_df[(patrimoine_df['doc_item_collection_ccode'] == 'AAPPRLP') & (patrimoine_df['sll_acq'] == 'oui')])}")

dont livres d'artistes : acquisitions : 0

### Publications en séries

In [111]:
data = patrimoine_df[patrimoine_df['sll_collection'] == 'D1 - Publications en série imprimées']
print(f"fonds : {len(data)}")

fonds : 2201

In [112]:
print(f"acquisitions : {len(data[data['sll_acq'] == 'oui'])}")

acquisitions : 919

### Cartes

In [113]:
data = patrimoine_df[patrimoine_df['sll_collection'] == 'D3 – Documents cartographiques']
print(f"Fonds : {len(data)}")
print(f"Acquisitions : {len(data[data['sll_acq'] == 'oui'])}")

Fonds : 0
Acquisitions : 0

### Partitions

In [114]:
data = patrimoine_df[patrimoine_df['sll_collection'] == 'D3 – Musique imprimée']
print(f"Fonds : {len(data)}")
print(f"Acquisitions : {len(data[data['sll_acq'] == 'oui'])}")

Fonds : 1664
Acquisitions : 0

### Documents iconographiques

In [115]:
data = patrimoine_df[patrimoine_df['sll_collection'] == 'D3 - Documents graphiques']
print(f"Fonds : {len(data)}")
print(f"Acquisitions : {len(data[data['sll_acq'] == 'oui'])}")

Fonds : 94
Acquisitions : 0

### Documents sonores

In [116]:
data = patrimoine_df[patrimoine_df['sll_collection'].isin(['D4 - Documents audiovisuels fonds adultes / Documents sonores : musique',
                                                           'D4 - Documents audiovisuels fonds adultes / Documents sonores : livres enregistrés'])]
print(f"Fonds : {len(data)}")
print(f"Acquisitions : {len(data[data['sll_acq'] == 'oui'])}")

Fonds : 22575
Acquisitions : 45

### Images animées

In [117]:
data = patrimoine_df[patrimoine_df['sll_collection'].isin(['D4 - Documents audiovisuels fonds adultes / documents vidéo adultes',
                                                           'D4 - Documents audiovisuels fonds enfants / documents vidéo enfants'])]
print(f"Fonds : {len(data)}")
print(f"Acquisitions : {len(data[data['sll_acq'] == 'oui'])}")

Fonds : 645
Acquisitions : 0

D1 - Livres imprimés                                                                  205053
D4 - Documents audiovisuels fonds adultes / Documents sonores : musique                45233
D4 - Documents audiovisuels fonds adultes / documents vidéo adultes                    12067
D1 - Publications en série imprimées                                                    9173
D3 – Musique imprimée                                                                   3193
D4 - Documents audiovisuels fonds enfants / documents vidéo enfants                     1593
D4 - Documents audiovisuels fonds adultes / Documents sonores : livres enregistrés      1541
D4 - Documents audiovisuels fonds enfants / Documents sonores : musique                  901
D4 - Total documents multimédia sur support                                              287
D4 - Documents audiovisuels fonds enfants / Documents sonores : livres enregistrés       218
D3 – Documents cartographiques                                                           125
D3 - Documents graphiques                                                                 93
D3 - Autres documents                                                                     83

### K241 Entrées par dons, keg et dations - Fonds

### K242 Entrées par dons, legs et dations - Acquisitions